export const fileType = new Map([
    ['image/gif', 'gif'],
    ['image/jpeg', 'jpg'],
    ['image/png', 'png'],
    ['application/octet-stream', 'rar'],
    ['application/zip', 'zip'],
    ['application/x-zip-compressed', 'zip'],
    ['video/avi', 'avi'],
    ['application/vnd.rn-realmedia-vbr', 'rmvb'],
    ['audio/mpeg', 'mp3'],
    ['text/plain', 'txt'],
    ['application/msword', 'doc'],
    ['application/vnd.ms-excel', 'xls'],
    ['application/vnd.ms-powerpoint', 'ppt'],
    ['application/pdf', 'pdf'],
    ['text/html', 'html'],
    ['application/java', 'class'],
    ['application/vnd.openxmlformats-officedocument.spreadsheetml.sheet', 'xlsx'],
    // ['application/octet-stream', 'con'],
    // ['image/bmp', 'bmp'],
    // ['application/octet-stream', 'psd'],
    // ['image/x-icon', 'ico'],
    // ['application/octet-stream', 'exe'],
    // ['application/octet-stream', '3gp'],
    // ['application/octet-stream', 'flv'],
    // ['audio/wav', 'wav'],
    // ['application/octet-stream', 'krc'],
    // ['application/octet-stream', 'lrc'],
    // ['application/octet-stream', 'chm'],
    // ['application/msaccess', 'mdb'],
    // ['text/plain', 'sql'],
    // ['text/plain', 'log'],
    // ['text/plain', 'dat'],
    // ['application/octet-stream', 'ini'],
    // ['application/octet-stream', 'php'],
    // ['text/html', 'htm'],
    // ['application/octet-stream', 'ttf'],
    // ['application/octet-stream', 'fon'],
    // ['text/html', 'js'],
    // ['text/xml', 'xml'],
    // ['application/octet-stream', 'dll'],
    // ['application/vnd.openxmlformats-officedocument.presentationml.presentation', 'pptx'],
    // ['application/vnd.openxmlformats-officedocument.wordprocessingml.document', 'docx'],
]);
